### ISSUE TITLE
CodeLens support

### ISSUE THREAD

**Issue by divyenduz** [Microsoft/typescript-template-language-service-decorator#10]
I am planning to take up [CodeLens](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/baseCodeLensProvider.ts#L54) implementation in the interface. 

I will use this feature to further augment GraphQL Language Service into TypeScript language service, mainly for [VSCode GraphQL extension](https://github.com/prismagraphql/vscode-graphql). 

I suppose this is the right place implement that as the extension already relies on this package.

**Comment by divyenduz** [comment]
From my understanding, code lens is specific to VSCode i.e. the language service in VSCode will need to be augmented. 

Which brings me to this question that is this project specific to VSCode or generic? 

Thanks!

**Comment by mjbvz** [comment]
Yes, the library is generic. You can only augment the typescript's api and cannot access the VS Code api directly.

This means that you can only hook into code lenses that VS Code gets from typescript, such as the `references` or `implementations` code lenses. These are powered by the `references` and `implementations` api in typescript

**Comment by divyenduz** [comment]
Ah! I that case I won't be able to provide CodeLens for tagged template literals I think. As they do not fall under `references` or `implementations` (I think). Will explore and revert. Thanks!
