### ISSUE TITLE
Error - Cannot find name 'AsyncIterator'

### ISSUE THREAD

**Issue by divyenduz** [Microsoft/typescript-template-language-service-decorator#11]
When I clone the project and run `tsc` I get this error.
Solution is to add `lib = ["es2015", "esnext"]` to `tsconfig.json`

Can we add it be default or extract AsyncIterator and keep it inline with the codebase?

**Comment by mjbvz** [comment]
What version of tsc are using using? Does this happen if you run `npm run compile`?

**Comment by divyenduz** [comment]
`tsc` is `2.8.4`

I am also able to observe this with `npm run compile`

**Comment by mjbvz** [comment]
I can't repo this and it also seems to build fine on travis: https://travis-ci.org/Microsoft/typescript-template-language-service-decorator/builds/407753482

What node version are you on? Can you also try re-installing the node modules to make sure you have the correct ts version

**Comment by mjbvz** [comment]
Closing as not reproducible
