### ISSUE TITLE
example

### ISSUE THREAD

**Issue by ecSpl01t** [Microsoft/typescript-template-language-service-decorator#14]
Hi,
I'm just started to learn the typescript language service plugin and I'm trying to understand your example and I don't understand the sentence "This plugin will now add echo completions to all template strings tagged with echo.", could you please provide more examples?
and where can I get documentation about it, because here [Writing-a-Language-Service-Plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) not enough.

Last question:
I got **typescript-plugin-example** from git and that's plugin works into Atom IDE but into Intellij IDE doesn't, do you know why ?

**Comment by mjbvz** [comment]
The documentation links to two real world example plugins you can investigate to see how they are implemented: https://github.com/Microsoft/typescript-template-language-service-decorator#examples
