### ISSUE TITLE
Typescript code as a result

### ISSUE THREAD

**Issue by rafalsobota** [microsoft/typescript-template-language-service-decorator#15]
Hi!
Sorry for such a simple question.  I'm looking for a template language that targets typescript code as a return value. I'm using basic string interpolation and looking for something more convenient. Is it possible to use this tool for this case?

**Comment by mjbvz** [comment]
Can you share an example?

**Comment by rafalsobota** [comment]
Sure

simple string substitution:
```
`import { Application } from 'express';

export function createController(app: Application) {
  app.get('/${_.kebabCase(entity.pluralName)}', (req, res) => {
    res.send([]);
  })
}
`
```

variableNames substitution and blocks of code:
```
`import express from 'express';
${entities.map(entity => `import * as ${entity.name} from './controllers/${_.kebabCase(entity.name)}';`).join('\n')}

const app = express();

${entities.map(entity => `${entity.name}.createController(app);`).join('\n')}

app.listen(8080);
`
```

**Comment by mjbvz** [comment]
Yes, this library can help you write editor tooling for languages embedded in template strings. It will not help you parse typescript inside of template strings (and my advice is to think long and hard about if you really want to stick typescript in strings)

**Comment by rafalsobota** [comment]
Thanks for advice. I moved to handlebars templates for now.

And good job with Typescript ecosystem. Thanks also for that
