### ISSUE TITLE
Publish new version that fixes getSupportedCodeFixes to support TS 5.0

### ISSUE THREAD

**Issue by vilic** [microsoft/typescript-template-language-service-decorator#27]
Hi @mjbvz, I found that the fix for `getSupportedCodeFixes` related issue already merged for months. Did you forget to release a new version to NPM?

**Comment by Aluisio** [comment]
please publish the new version because with vs code update to version 1.77 all styled components users are not able to use intellisense

**Comment by usercao** [comment]
please publish the new version because with vs code update to version 1.77 all styled components users are not able to use intellisense

**Comment by mjbvz** [comment]
Published as  2.3.2
