### ISSUE TITLE
Please consider removing tag regex escaping

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/typescript-template-language-service-decorator#6]
Due to [this line](https://github.com/Microsoft/typescript-template-language-service-decorator/blob/05c9aa3b604e88be4c50b708fde544f6a694b267/src/nodes.ts#L62) it's impossible to use regular expression to define tags to match. Also identifiers can't have these special regex symbols anyway, and you can always escape them by self if you need.

Use case:

```ts
const A = styled<Props>("button") `color: red;`
```

Ideally i want to define tags in ```typescript-styled-plugin``` as:
```json
{
                "tags": [
                    "styled",
                    "styled<.*>\\(.*\\)"
                ]
}
```

**Comment by mjbvz** [comment]
I think #8 is a better approach here; let libraries provide a custom function that determines if they apply to a given tagged template or not
