### ISSUE TITLE
Inject the tags option dynamically

### ISSUE THREAD

**Issue by divyenduz** [Microsoft/typescript-template-language-service-decorator#8]
Hey! we are using this in context of GraphQL for providing language features and an interesting use case is that in one TS/JS file you can have `gql` tags belonging to different schemas. 

So, we might want to have something like

`gql1` or `gql2` that might changing at runtime in context of the VSCode plugin.

Or even something like

`gql.app1` or `gql.app2` (can we already specify a tag that has a "." in it?)

Do you think that something like this is possible in context of this project?

This idea is still in early stage but I am opening this issue to
1. Make you aware of the approach we are thinking of - maybe you ran into this before
2. Seeking your view on the issue

Thanks!

**Comment by mjbvz** [comment]
Yes this should be possible. For the first part, we just would need to make the tagged template detection dynamic. My thought is that consumers of this library would basically provide a `isSupportedTaggedTemplate` function that we would check on every possible tagged template node in a given file

The problem you will likely run into is how to get information from VS Code to the plugin. There is no direct communications channel so you currently either have to use the configuration options in the `tsconfig.json` or `jsconfig.json`, or establish an external communications channel. 

Does the dynamic template detection part make sense at least?

**Comment by divyenduz** [comment]
Linking [this repository](https://github.com/mjbvz/vscode-comment-tagged-templates) here because I think it addresses the part about getting information from "VS Code to the plugin" for my future self or whoever picks this up :)

**Comment by mjbvz** [comment]
Closing in favor of #13
